export { default as Landing } from './Landing'
export { default as HomeLayout } from './HomeLayout'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as WhishList } from './WhishList'
export { default as Cart } from './Cart'
export { default as About } from './About'
export { default as Contact } from './Contact'
