import gamePad from './assets/products/gamepad.png'
import chair from './assets/products/chair.png'
import keyboard from './assets/products/keyboard.png'
import screen from './assets/products/screen.png'
import p1 from './assets/products/547953_9C2ST_8746_001_082_0000_Light-Gucci-Savoy-medium-duffle-bag 1.png'
import p2 from './assets/products/672462_ZAH9D_5626_002_100_0000_Light-The-North-Face-x-Gucci-coat 1.png'
import p3 from './assets/products/gammaxx-l240-argb-1-500x500 1.png'
import p4 from './assets/products/sam-moghadam-khamseh-L_7MQsHl_aU-unsplash 1.png'
import { nanoid } from 'nanoid'
export const flashSaleData = [
  {
    id: nanoid(),
    name: 'HAVIT HV-G92 Gamepad',
    price: 160,
    discount: 120,
    image: gamePad,
    review: { stars: 4, rate: 88 },
    amount: 5,
    flashSale: true,
  },
  {
    id: nanoid(),
    name: 'AK-900 Wired Keyboard',
    price: 1160,
    discount: 960,
    image: keyboard,
    review: { stars: 4, rate: 75 },
    amount: 5,
    flashSale: true,
  },
  {
    id: nanoid(),
    name: 'IPS LCD Gaming Monitor',
    price: 400,
    discount: 370,
    image: screen,
    review: { stars: 4, rate: 88 },
    amount: 5,
    flashSale: true,
  },
  {
    id: nanoid(),
    name: 'S-Series Comfort Chair',
    price: 400,
    discount: 375,
    image: chair,
    review: { stars: 4, rate: 88 },
    amount: 5,
    flashSale: true,
  },
  {
    id: nanoid(),
    name: 'The north coat',
    price: 360,
    discount: 260,
    image: p2,
    review: { stars: 5, rate: 65 },
    amount: 5,
    bestSelling: true,
  },
  {
    id: nanoid(),
    name: 'Small BookSelf',
    price: null,
    discount: 360,
    image: p1,
    review: { stars: 4, rate: 75 },
    amount: 5,
    bestSelling: true,
  },
  {
    id: nanoid(),
    name: 'Gucci duffle bag',
    price: 1160,
    discount: 960,
    image: p3,
    review: { stars: 4.5, rate: 65 },
    amount: 5,
    bestSelling: true,
  },
  {
    id: nanoid(),
    name: 'RGB liquid CPU Cooler',
    price: 170,
    discount: 160,
    image: p4,
    review: { stars: 4.3, rate: 67 },
    amount: 5,
    bestSelling: true,
  },
  {
    id: nanoid(),
    name: 'HAVIT HV-G92 Gamepad',
    price: 160,
    discount: 120,
    image: gamePad,
    review: { stars: 4, rate: 88 },
    amount: 5,
  },
  {
    id: nanoid(),
    name: 'AK-900 Wired Keyboard',
    price: 1160,
    discount: 960,
    image: keyboard,
    review: { stars: 4, rate: 75 },
    amount: 5,
  },
  {
    id: nanoid(),
    name: 'IPS LCD Gaming Monitor',
    price: 400,
    discount: 370,
    image: screen,
    review: { stars: 4, rate: 88 },
    amount: 5,
  },
  {
    id: nanoid(),
    name: 'S-Series Comfort Chair',
    price: 400,
    discount: 375,
    image: chair,
    review: { stars: 4, rate: 88 },
    amount: 5,
  },
  {
    id: nanoid(),
    name: 'The north coat',
    price: 360,
    discount: 260,
    image: p2,
    review: { stars: 5, rate: 65 },
    amount: 5,
  },
  {
    id: nanoid(),
    name: 'Small BookSelf',
    price: null,
    discount: 360,
    image: p1,
    review: { stars: 4, rate: 75 },
    amount: 5,
  },
  {
    id: nanoid(),
    name: 'Gucci duffle bag',
    price: 1160,
    discount: 960,
    image: p3,
    review: { stars: 4.5, rate: 65 },
    amount: 5,
  },
  {
    id: nanoid(),
    name: 'RGB liquid CPU Cooler',
    price: 170,
    discount: 160,
    image: p4,
    review: { stars: 4.3, rate: 67 },
    amount: 5,
  },
]
